# Generated by Django 5.2.1 on 2025-08-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
