# Generated by Django 5.2.1 on 2025-08-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='About',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='post',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='post',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hire',
        ),
        migrations.RemoveField(
            model_name='post',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='services',
        ),
        migrations.RemoveField(
            model_name='post',
            name='testimonial',
        ),
    ]
